.circleci/config.yml
Increase persistent volume size from 1500Gi --> 2000Gi
=> Ethereum Daemon Volume Resize

.circleci/config.yml, node/coinstacks/bitcoin/pulumi/Pulumi.sample.yaml, node/coinstacks/bitcoin/pulumi/config.ts, node/coinstacks/common/pulumi/src/api.ts, node/coinstacks/ethereum/pulumi/Pulumi.sample.yaml, node/coinstacks/ethereum/pulumi/config.ts
This PR allows for the deployment of a horizontal pod autoscaler alongside asset API's. This will enable us to run with lower resource requests and scale horizontally to meet demand.
=> API Autoscaling

.github/ISSUE_TEMPLATE/bounty.yml, .github/ISSUE_TEMPLATE/config.yml
taking over from https://github.com/shapeshift/unchained/pull/249
=> docs: bounty template

node/packages/parser/src/ethereum/index.ts
@kaladinlight a quick refactor as an example of what we briefly DMed about.
IMO this makes the logic a little easier to follow and could reduce developer error.
=> refactor: use getParsedTxWithTransfers for clarity

node/coinstacks/bitcoin/ingester/src/workers/address.ts, node/coinstacks/ethereum/ingester/src/workers/address.ts, node/packages/parser/src/bitcoin/index.ts, node/packages/parser/src/ethereum/index.ts
A small variable naming update, suggested by @gomesalexandre in https://github.com/shapeshift/unchained/pull/260#discussion_r808776897.
=> refactor: pTx -> parsedTx

.circleci/config.yml
Add TaxiStake AWS NAT addresses to traefik whitelist
=> TaxiStake NAT Whitelist

.circleci/config.yml
Remove development resources from the TaxiStake unchained cluster.
=> Remove TaxiStake Develop

go/coinstacks/cosmos/api/types.go, go/coinstacks/osmosis/api/types.go, go/coinstacks/thorchain/api/types.go, go/pkg/cosmos/tx.go
return tx events mapped by message index. allows us to easily match up log events with corresponding messages
=> return tx events mapped by message index

go/coinstacks/cosmos/api/handlers.go, go/pkg/cosmos/block.go
=> add debug logs for cosmos

go/coinstacks/cosmos/api/handlers.go, go/pkg/cosmos/block.go
=> Debug logs cosmos3

go/coinstacks/cosmos/api/handlers.go, go/pkg/cosmos/block.go
remove debug logs and add nil checks
=> remove debug logs and add nil checks

go/coinstacks/cosmos/api/handlers.go, go/go.mod, go/go.sum
Account & info endpoints now make their calls to cosmos nodes asynchronously
=> Account & info endpoints make calls asynchronously

node/coinstacks/bitcoin/api/package.json, node/coinstacks/bitcoin/ingester/package.json, node/coinstacks/bitcoin/pulumi/package.json, node/coinstacks/common/api/package.json, node/coinstacks/common/ingester/package.json, node/coinstacks/common/mongo/package.json, node/coinstacks/common/pulumi/package.json, node/coinstacks/ethereum/api/package.json, node/coinstacks/ethereum/ingester/package.json, node/coinstacks/ethereum/pulumi/package.json, node/lerna.json, node/packages/blockbook/package.json, node/packages/blockbook/pulumi/package.json, node/packages/client/package.json, node/pulumi/package.json
=> chore(release): publish 6.9.0

node/packages/client/src/websocket.ts
- Throw if connection does not succeed within 5 seconds
=> Add connection timeout

.circleci/config.yml
Reverts shapeshift/unchained#499
=> Revert "chore: upgrade midgard to v2.9.4"

node/coinstacks/common/api/src/evm/service.ts
- delete tx from pending set when returned in page response
=> fix: eth pending txhistory bug

.circleci/config.yml, go/coinstacks/cosmos/api/swagger.json
- ensure accurate and up to date swagger.json is tracked in source for client generation
=> feat: add postcheck operation to push any swagger file updates

node/packages/blockbook/Dockerfile
https://github.com/trezor/blockbook/issues/820
=> fix: update blockbook to fix message size limit error

.circleci/config.yml, go/cmd/osmosis/main.go, go/cmd/osmosis/sample.env, go/cmd/thorchain/sample.env, go/coinstacks/cosmos/daemon/init.sh, go/coinstacks/cosmos/daemon/readiness.sh, go/coinstacks/cosmos/pulumi/index.ts, go/coinstacks/osmosis/api/api.go, go/coinstacks/osmosis/api/handler.go, go/coinstacks/osmosis/daemon/init.sh, go/coinstacks/osmosis/daemon/readiness.sh, go/coinstacks/osmosis/osmosis.go, go/coinstacks/osmosis/pulumi/index.ts, go/coinstacks/osmosis/tx.go, go/pkg/cosmos/tx.go, node/coinstacks/avalanche/daemon/config.json, node/coinstacks/avalanche/daemon/init.sh, node/coinstacks/avalanche/pulumi/index.ts, pulumi/src/statefulService.ts
- avalanche
- cosmos
- osmosis
=> feat: self hosted nodes

go/pkg/websocket/websocket.go
- gorilla websockets do not support concurrent writes. add mutex lock to prevent this panic case
=> fix: mutex lock to prevent concurrent write panic

node/coinstacks/ethereum/daemon/init.sh, node/coinstacks/ethereum/pulumi/index.ts
- open up websocket connections at `/websocket`
=> feat: expose ethereum websockets

node/coinstacks/avalanche/api/package.json, node/coinstacks/avalanche/api/src/controller.ts, node/coinstacks/avalanche/api/src/swagger.json, node/coinstacks/common/api/package.json, node/coinstacks/common/api/src/evm/models.ts, node/coinstacks/common/api/src/evm/service.ts, node/coinstacks/ethereum/api/package.json, node/coinstacks/ethereum/api/src/controller.ts, node/coinstacks/ethereum/api/src/swagger.json, node/coinstacks/optimism/api/package.json, node/coinstacks/optimism/api/src/controller.ts, node/coinstacks/optimism/api/src/models.ts, node/coinstacks/optimism/api/src/swagger.json, node/yarn.lock
**BREAKING CHANGE: response payload changed for /gas/estimate to allow handling additional estimates like l1 gas limit on optimism**
- leverage `eth-optimism` packages to estimate `gasLimit` and `gasPrice` as determined by the current state of the [Gas Price Oracle](https://optimistic.etherscan.io/address/0x420000000000000000000000000000000000000F)
=> feat: optimism l1 fees

.circleci/config.yml, pulumi/src/config.ts, pulumi/src/index.ts, pulumi/src/statefulService.ts
- osmosis no limit (getting 137 OOM trying to spin up, will monitor resource usage to tune after stable)
=> chore: support request/limit for resources

go/Makefile, go/coinstacks/cosmos/api/api.go, go/coinstacks/osmosis/api/api.go, go/coinstacks/thorchain/api/api.go
- there appears to be a memory leak in the cosmossdk apis. add pprof for debugging
=> chore: add pprof server

.circleci/config.yml, node/packages/blockbook/Dockerfile
- includes upstream bnbsmartchain
=> chore: update blockbook to master@15c19ac (add bsc)

.circleci/config.yml
https://github.com/ethereum/go-ethereum/releases/tag/v1.11.5
**- enables shanghai upgrade**
=> chore: upgrade geth v1.11.4 -> v1.11.5

.circleci/config.yml, node/coinstacks/bnbsmartchain/pulumi/index.ts
- maybe more resources and IOPS and new snapshot sync will keep this god forsaken chain in sync....
=> chore: increase resources and restore from new public snapshot

.circleci/config.yml, node/coinstacks/bnbsmartchain/daemon/init.sh
testing in dev 1.1.21 seems more stable than 1.1.22 and give it all of the peers
=> fix: more bsc tweaks

.circleci/config.yml
=> fix: eth cron

.circleci/config.yml, node/packages/blockbook/Dockerfile
- thornode `v1.108.1`
- blockbook `fdc2b86`
=> chore: upgrade thornode and blockbook

.circleci/config.yml, node/coinstacks/bnbsmartchain/daemon/Dockerfile
https://github.com/bnb-chain/bsc/releases/tag/v1.1.23 fixes bug introduced in v1.1.22
- tune resources
- use alpine image
=> chore: upgrade bsc v1.1.21 -> v1.1.23

pulumi/package.json, pulumi/src/snapper.ts, yarn.lock
- Add namespace arg to make sure volume snapshots are made in the correct namespace
- Added error handling so that even when a snapshot fails, the stateful set is scaled back up
=> fix: added error snapper handling and fixed namespace issue

.circleci/config.yml
- geth v1.11.5 -> v1.11.6
- prysm v4.0.2 -> v4.0.3
=> chore: upgrade ethereum backend

.circleci/config.yml, pulumi/package.json, yarn.lock
=> feat: traefic hpa

pulumi/src/statefulService.ts
Better condition for snapshots so that we're not using the wrong ones
=> fix: snapshot query

.circleci/config.yml
https://github.com/ava-labs/avalanchego/releases/tag/v1.10.1
=> chore: upgrade avalanche v1.10.0 -> v1.10.1

.circleci/config.yml
https://github.com/cosmos/gaia/releases/tag/v9.1.0
=> chore: upgrade cosmos v9.0.3 -> v9.1.0

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v1.109.1
=> chore: upgrade thorchain v1.109.0 -> v1.109.1

.circleci/config.yml
=> chore: increase thornode volume size

.circleci/config.yml
https://github.com/maticnetwork/bor/releases/tag/v0.3.9
=> chore: upgrade polygon bor v0.3.7 -> v0.3.9

monitoring/my-kube-prometheus/build.sh, monitoring/my-kube-prometheus/unchained-kube-promstack.jsonnet, monitoring/src/config.ts, monitoring/src/grafana.ts, monitoring/src/index.ts
* Set a constant grafana admin password, injected in CI
* Fix the DNS routing on grafana panel
=> chore: grafana dns + password

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v1.110.0
=> chore: upgrade thorchain v1.109.2 -> v1.110.0

.circleci/config.yml
https://github.com/prysmaticlabs/prysm/releases/tag/v4.0.5
=> chore: upgrade prysm v4.0.3 -> v4.0.5

.circleci/config.yml
https://github.com/cosmos/gaia/releases/tag/v10.0.0
=> chore: upgrade cosmos v9.1.0 -> v10.0.0

.circleci/config.yml
https://github.com/bnb-chain/bsc/releases/tag/v1.2.4
=> chore: upgrade bsc v1.1.23 -> v1.2.4

.circleci/config.yml
https://github.com/sigp/lighthouse/releases/tag/v4.2.0
https://github.com/NethermindEth/nethermind/releases/tag/1.18.1
=> chore: upgrade gnosis

.circleci/config.yml
Reverts shapeshift/unchained#755
=> Revert "chore: upgrade cosmos v9.1.0 -> v10.0.0"

.circleci/config.yml, node/coinstacks/bitcoin/daemon/Dockerfile
https://github.com/bitcoin/bitcoin/releases/tag/v25.0
=> chore: upgrade bitcoin v24.0.1 -> v25.0

.circleci/config.yml
https://github.com/cosmos/gaia/releases/tag/v9.1.1
=> chore: upgrade cosmos v9.1.0 -> v9.1.1

node/coinstacks/polygon/daemon/init.sh, node/coinstacks/polygon/heimdall/init.sh
more robust snapshot recovery/retry configuration to ensure download from snapshot completes fully
=> chore: polygon snapshot recover

.circleci/config.yml
https://github.com/maticnetwork/heimdall/releases/tag/v0.3.4
=> chore: upgrade heimdall v0.3.3 -> v0.3.4

.circleci/config.yml
https://github.com/ava-labs/avalanchego/releases/tag/v1.10.3
=> chore: upgrade avalanche v1.10.2 -> v1.10.3

.circleci/config.yml
https://hub.docker.com/layers/0xpolygon/heimdall/0.3.4/images/sha256-43ec058966cf2b7bf99f60881030121b04d8183a1b5e9e98cd5afc31151dd001?context=explore
=> chore: heimdall v0.3.4-beta -> v0.3.4

.circleci/config.yml
https://github.com/prysmaticlabs/prysm/releases/tag/v4.0.6
=> chore: upgrade prysm v4.0.5 -> v4.0.6

.circleci/config.yml
https://github.com/cosmos/gaia/releases/tag/v10.0.1
DO NOT MERGE UNTIL UPGRADE HEIGHT: https://www.mintscan.io/cosmos/blocks/15816200
=> chore: upgrade cosmos v9.1.1 -> v10.0.1

.circleci/config.yml
https://github.com/bnb-chain/bsc/releases/tag/v1.2.8
=> chore: upgrade bsc v1.2.7 -> v1.2.8

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/tags/v1.114.0
=> chore: upgrade thorchain v1.113.1 -> v1.114.0

pulumi/src/coinstack.ts, pulumi/src/statefulService.ts
Removed snapshots to prevent roll on deploy
=> chore: removed snapshotting

.circleci/config.yml
https://github.com/NethermindEth/nethermind/releases/tag/1.19.3
=> chore: upgrade gnosis v1.19.2 -> v1.19.3

.circleci/config.yml
https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.1.1
=> chore: upgrade op-node v1.1.0 -> v1.1.1

.circleci/config.yml
https://github.com/maticnetwork/bor/releases/tag/v0.4.0
=> chore: upgrade polygon v0.3.9 -> v0.4.0

go/coinstacks/osmosis/tx.go, go/coinstacks/thorchain/events.go, go/coinstacks/thorchain/tx.go, go/pkg/cosmos/models.go, go/pkg/cosmos/tx.go
explicitly track message index for associating with the event logs later on
=> feat: track message index

.circleci/config.yml
https://github.com/NethermindEth/nethermind/releases/tag/1.20.0
=> chore: upgrade gnosis nethermind v1.19.3 -> v1.20.0

.circleci/config.yml
https://github.com/osmosis-labs/osmosis/releases/tag/v16.1.0
=> chore: upgrade osmosis v15.2.0 -> v16.1.0

.circleci/config.yml
https://discord.com/channels/838986635756044328/839002272654426122/1130958337412960308
=> chore: upgrade thorchain image to use mainnet branch

.circleci/config.yml
https://github.com/osmosis-labs/osmosis/releases/tag/v16.1.1
=> chore: upgrade osmosis v16.1.0 -> v16.1.1

.circleci/config.yml
https://github.com/ava-labs/avalanchego/releases/tag/v1.10.7
=> chore: upgrade avalanche v1.10.4 -> v1.10.7

.circleci/config.yml
https://github.com/bnb-chain/bsc/releases/tag/v1.2.10
=> chore: upgrade bsc v1.2.8 -> v1.2.10

.circleci/config.yml
https://github.com/NethermindEth/nethermind/releases/tag/1.20.1
=> chore: upgrade gnosis nethermind v1.20.0 -> v1.20.1

.circleci/config.yml, pulumi/src/index.ts, pulumi/src/statefulService.ts
also enforces limits on stateful services to help with cluster autoscaler
=> chore: right size api services

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v1.119.0
=> chore: upgrade thorchain v1.118.0 -> v1.119.0

k6/Makefile, monitoring/src/dashboards/overview.json, monitoring/src/index.ts
- update k6 load test docker image
- break out regex functions to catch necessary conditions better
- increase prometheus volume size
=> chore: regex cleanup

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v1.120.0
=> chore: upgrade thorchain v1.119.0 -> v1.120.0

.circleci/config.yml
- will need to run this locally with a preview to make sure the diff looks accurate and doesn't tear down our eks nodes...
=> chore: turn off eks autoscaling

.circleci/config.yml, node/coinstacks/gnosis/daemon/init.sh
https://github.com/ethereum/go-ethereum/releases/tag/v1.13.2
https://github.com/ava-labs/avalanchego/releases/tag/v1.10.11
https://gitlab.com/thorchain/thornode/-/releases/v1.121.0
https://gitlab.com/thorchain/midgard/-/releases/2.17.1
https://github.com/maticnetwork/bor/releases/tag/v1.0.4
https://github.com/NethermindEth/nethermind/releases/tag/1.21.0
https://github.com/sigp/lighthouse/releases/tag/v4.5.0
TODO: follow up with heimdall upgrade https://github.com/maticnetwork/heimdall/releases/tag/v1.0.1
=> chore: infra maintenance

.circleci/config.yml
https://github.com/ethereum/go-ethereum/releases/tag/v1.13.3
https://github.com/cosmos/gaia/releases/tag/v13.0.0
https://github.com/ava-labs/avalanchego/releases/tag/v1.10.12
https://github.com/maticnetwork/heimdall/releases/tag/v1.0.2
https://github.com/maticnetwork/bor/releases/tag/v1.0.6
=> chore: upgrade nodes

.circleci/config.yml, go/build/Dockerfile.daemon, go/coinstacks/cosmos/Makefile, go/coinstacks/thorchain/Makefile, go/scripts/run.sh
- right size volumes based on recent changes
- upgrade `go-swagger` to `v0.30.5`
- pull omnibus build artifacts into unchained (closes https://github.com/shapeshift/unchained/issues/653)
- add `docker` make target for cosmos daemon image
node upgrades:
https://github.com/ethereum/go-ethereum/releases/tag/v1.13.5
https://github.com/maticnetwork/bor/releases/tag/v1.1.0
=> chore: infra updates

.circleci/config.yml, node/coinstacks/polygon/pulumi/index.ts
https://github.com/trezor/blockbook/pull/994
=> perf: evm blockbook spam tx fix

.circleci/config.yml
https://github.com/ava-labs/avalanchego/releases/tag/v1.10.16
=> chore: upgrade avalanche v1.10.15 -> v1.10.16

go/coinstacks/cosmos/api/api.go, go/coinstacks/cosmos/api/handler.go, go/coinstacks/cosmos/api/swagger.json, go/pkg/cosmos/fees.go
- fetch global fees
- fetch local fees
- return the highest fee that will be enforced by the node
- supports multi denom fees
=> feat: add gas fees endpoint for cosmos

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v1.125.0
=> chore: upgrade thorchain v1.124.2 -> v1.125.0

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v1.125.1
=> chore: upgrade thorchain v1.125.0 -> v1.125.1

.circleci/config.yml
https://github.com/cosmos/gaia/releases/tag/v14.1.0
DO NOT MERGE UNTIL: https://www.mintscan.io/cosmos/block/18262000
=> chore: upgrade cosmos v13.0.2 -> v14.1.0

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v1.125.2
=> chore: upgrade thorchain v1.125.1 -> 1.125.2

.circleci/config.yml, node/coinstacks/bnbsmartchain/daemon/init.sh, node/coinstacks/bnbsmartchain/pulumi/index.ts
- bsc pebbledb + pbss
- volume size bumps
- also includes the thorchain node version bump due to current manual state of infra
=> feat: migrate bsc to pebbledb and pbss

.circleci/config.yml, node/coinstacks/bitcoin/api/src/controller.ts, node/coinstacks/bitcoincash/api/src/controller.ts, node/coinstacks/common/api/src/evm/service.ts, node/coinstacks/common/api/src/utxo/service.ts, node/coinstacks/dogecoin/api/src/controller.ts, node/coinstacks/litecoin/api/src/controller.ts, node/packages/blockbook/src/controller.ts, node/packages/blockbook/src/models.ts, node/packages/blockbook/src/websocket.ts
- prep codebase to handle api keys for nownodes endpoints
- some minor cleanup
=> feat: support rpc and indexer api keys

.circleci/config.yml, node/coinstacks/bitcoincash/api/src/app.ts, node/coinstacks/bitcoincash/api/src/controller.ts, node/coinstacks/bitcoincash/sample.env
~~**websockets broken upstream**~~
=> feat: nownodes bitcoincash

.circleci/config.yml, node/coinstacks/common/api/src/evm/service.ts, node/coinstacks/ethereum/api/src/app.ts, node/coinstacks/ethereum/api/src/controller.ts, node/coinstacks/ethereum/sample.env
**eth_maxPriorityFeePerGas unavailable upstream**
patching for missing `eth_maxPriorityFeePerGas` to unblock for now
=> feat: nownodes ethereum

.circleci/config.yml, node/coinstacks/bnbsmartchain/api/src/app.ts, node/coinstacks/bnbsmartchain/api/src/controller.ts, node/coinstacks/bnbsmartchain/sample.env
~~**websockets broken upstream**~~
**`debug_traceTransaction` not available upstream**
going to use our self hosted node for `debug_traceTransaction` for now to let blockbook support bake in dev
=> feat: nownodes bnbsmartchain

.circleci/config.yml, node/packages/blockbook/Dockerfile
https://github.com/bnb-chain/bsc/releases/tag/v1.3.8
https://github.com/ethereum-optimism/optimism/releases/tag/op-batcher%2Fv1.4.3
=> chore: blockbook and node upgrade

.circleci/config.yml, node/coinstacks/arbitrum/api/src/app.ts, node/coinstacks/arbitrum/api/src/controller.ts, node/coinstacks/arbitrum/sample.env
~~**`subscribeNewTransaction` not available upstream**~~
=> feat: nownodes arbitrum

.circleci/config.yml, node/coinstacks/dogecoin/api/src/app.ts, node/coinstacks/dogecoin/api/src/controller.ts, node/coinstacks/dogecoin/sample.env
~~**`subscribeNewTransactions` not available upstream**~~
=> feat: nownodes dogecoin

.circleci/config.yml, node/coinstacks/common/api/src/evm/service.ts, node/coinstacks/polygon/api/src/app.ts, node/coinstacks/polygon/api/src/controller.ts, node/coinstacks/polygon/sample.env
~~**websockets, tx history, and eth_maxPriorityFeePerGas broken upstream**~~
=> feat: nownodes polygon

.circleci/config.yml
- https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.1
- https://gitlab.com/thorchain/thornode/-/releases/v1.128.1
- https://github.com/maticnetwork/bor/releases/tag/v1.2.7
- https://github.com/maticnetwork/heimdall/releases/tag/v1.0.4
- https://github.com/sigp/lighthouse/releases/tag/v5.1.0
Also trigger pulumi `--refresh` to get all ephemeral state changes back in alignment with deploy
=> chore: upgrade nodes to latest versions

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v1.129.0
=> chore: upgrade thorchain v1.128.1 -> v1.129.0

node/packages/blockbook/src/websocket.ts
- don't throw on `subscribeAddresses` to prevent crash loop when websockets go down
- cache current subscribe address set to resubscribe on reconnect
=> fix: blockbook websocket management

.circleci/config.yml
Includes the following updates:
https://gitlab.com/thorchain/midgard/-/releases/2.20.0
https://gitlab.com/thorchain/midgard/-/releases/2.20.1
https://gitlab.com/thorchain/midgard/-/releases/2.21.0
https://gitlab.com/thorchain/midgard/-/releases/2.21.1
=> chore: upgrade midgard v2.19.1 -> v2.21.1

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v1.133.0
=> chore: upgrade thorchain v1.132.0 -> v1.133.0

.circleci/config.yml
https://github.com/ethereum/go-ethereum/releases/tag/v1.14.5
=> chore: upgrade ethereum v1.14.3 -> v1.14.5

.circleci/config.yml, go/coinstacks/thorchain/indexer/init.sh, go/coinstacks/thorchain/pulumi/index.ts
https://gitlab.com/thorchain/midgard/-/releases/2.22.3
=> chore: upgrade midgard v2.21.1 -> v2.22.3

.circleci/config.yml, node/coinstacks/base/daemon/init.sh, node/coinstacks/optimism/daemon/init.sh
- https://github.com/bitcoin/bitcoin/releases/tag/v27.1
- https://github.com/ethereum/go-ethereum/releases/tag/v1.14.6
- https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.4
- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101315.2
- https://github.com/ethereum-optimism/optimism/releases/tag/v1.7.7
- https://github.com/NethermindEth/nethermind/releases/tag/1.27.0
- https://github.com/sigp/lighthouse/releases/tag/v5.2.1
=> chore: version updates

.circleci/config.yml
- https://github.com/ethereum-optimism/optimism/releases/tag/v1.8.0
- https://github.com/ethereum/go-ethereum/releases/tag/v1.14.7
- https://gitlab.com/thorchain/thornode/-/releases/v1.134.0 (already running, just forgot to update the circle config)
- https://github.com/NethermindEth/nethermind/releases/tag/1.27.1
=> chore: update nodes

.circleci/config.yml
https://gitlab.com/thorchain/midgard/-/releases/2.23.2
=> chore: upgrade midgard v2.22.3 -> v2.23.2

.circleci/config.yml
- https://github.com/ethereum/go-ethereum/releases/tag/v1.14.8
- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101315.3
- https://github.com/ethereum-optimism/optimism/releases/tag/v1.9.0
- https://github.com/sigp/lighthouse/releases/tag/v5.3.0
=> chore: update node versions

.circleci/config.yml, node/coinstacks/gnosis/daemon/init.sh
- update to confirmed working blockbook image (no erc1155 indexing)
- increase prod replicas back to 2
- keep all tx receipts
=> chore: fucking finally gnosis confirmed working (no erc1155)

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v2.135.1
=> chore: upgrade thorchain v2.135.0 -> v2.135.1

.circleci/config.yml
https://gitlab.com/thorchain/thornode/-/releases/v2.136.0
=> chore: upgrade thorchain v2.135.1 -> v2.136.0

node/coinstacks/solana/api/src/controller.ts, node/coinstacks/solana/api/src/models.ts, node/coinstacks/solana/api/src/swagger.json, node/coinstacks/solana/sample.env
- simulate transaction to get compute unit cost for estimation
- add swagger doc examples
- add jsonrpc endpoint
=> feat: update solana estimation for compute units

go/coinstacks/thorchain-v1/api/websocket.go, go/pkg/cosmos/websocket.go, node/coinstacks/solana/api/src/websocket.ts, node/packages/blockbook/src/websocket.ts, node/packages/websocket/src/websocket.ts
- Add reset timeout to the websocket connections to reset the websocket subscriptions if no websocket message has been received within the timeout window while the connection is open and active
=> feat: websocket durability improvements

node/coinstacks/common/api/src/evm/gasOracle.ts
L2 fees are being estimated high due to large outlier fees throwing off the percentiles. Remove all fees outside a reasonable threshold to ensure estimated gas prices are sane against the median fee price.
=> feat: add fee threshold to gas oracle

node/coinstacks/common/api/src/evm/gasOracle.ts
For chains with low priority fees and fast block times, add a 2x base fee buffer to support successful transaction broadcast as base fee may increase by the time the transaction hits the node resulting in too low of fee with min priority fee. This will ensure the transaction will be valid for 6 consecutive full blocks which should provide enough time for the transaction to confirm on chain with viable gas price.
=> feat: add base fee buffer to gas oracle

CONTRIBUTING.MD
A bit of a false lie since we do not really expect unchained contributions, but gives us something nice to link to for spam PRs.
=> feat: add CONTRIBUTING.MD

.circleci/config.yml, node/packages/blockbook/Dockerfile
Brings in a recent change that should help improve sync performance:
https://github.com/trezor/blockbook/commit/19a902360ed93e5c2f7faa86577c64414448ecf7
=> chore: update blockbook

.circleci/config.yml
- https://gitlab.com/thorchain/thornode/-/releases/v3.1.1
- https://gitlab.com/thorchain/midgard/-/releases/2.29.0
=> chore: upgrade thorchain v3.1.0 -> v3.1.1

.circleci/config.yml
- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101411.4
- https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.10.2
- https://github.com/prysmaticlabs/prysm/releases/tag/v5.2.0
- https://github.com/NethermindEth/nethermind/releases/tag/1.30.3
- https://github.com/sigp/lighthouse/releases/tag/v6.0.1
=> chore: upgrade infra

.circleci/config.yml, node/coinstacks/base/op-node/init.sh
- https://github.com/ethereum/go-ethereum/releases/tag/v1.15.2
- https://github.com/prysmaticlabs/prysm/releases/tag/v5.3.0
- https://github.com/NethermindEth/nethermind/releases/tag/1.31.0
- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101500.0
- https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.11.1
=> chore: update backend images

.circleci/config.yml
- https://github.com/ethereum/go-ethereum/releases/tag/v1.15.3
- https://github.com/NethermindEth/nethermind/releases/tag/1.31.2
- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101500.1
- https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.11.2
=> chore: upgrade node versions

.circleci/config.yml, node/coinstacks/base/pulumi/index.ts
- https://github.com/ethereum/go-ethereum/releases/tag/v1.15.5
- https://github.com/prysmaticlabs/prysm/releases/tag/v5.3.1
- https://gitlab.com/thorchain/thornode/-/releases/v3.3.1
- https://github.com/NethermindEth/nethermind/releases/tag/1.31.5
- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101503.1
- https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.12.1
- right sizing
- remove bitcoin sts and fallback deployment
=> chore: backend updates

node/coinstacks/base/daemon/init.sh, node/coinstacks/base/op-node/init.sh, node/coinstacks/base/pulumi/index.ts
Update our base config with the latest config published by base: https://github.com/base/node/blob/main/.env.mainnet
Please lord let this stabilize things :hocho: :goat: :drop_of_blood: :pray: :full_moon: :magic_wand: :beer:
=> chore: base config updates

node/coinstacks/common/api/src/utxo/service.ts
Prevent floating point precision issues
=> fix: use bignumber for fee math

node/coinstacks/arbitrum-nova/api/src/controller.ts, node/coinstacks/arbitrum/api/src/controller.ts, node/coinstacks/avalanche/api/src/controller.ts, node/coinstacks/base/api/src/controller.ts, node/coinstacks/bnbsmartchain/api/src/controller.ts, node/coinstacks/common/api/src/evm/models.ts, node/coinstacks/common/api/src/evm/service.ts, node/coinstacks/common/api/src/models.ts, node/coinstacks/ethereum/api/src/controller.ts, node/coinstacks/gnosis/api/src/controller.ts, node/coinstacks/optimism/api/src/controller.ts, node/coinstacks/polygon/api/src/controller.ts, node/coinstacks/polygon/api/src/swagger.json
TODO: remove get endpoint after web migration
=> feat: add post endpoint for estimate gas

.circleci/config.yml
DO NOT MERGE UNTIL UPGRADE BLOCK: https://runescan.io/block/22198000
- https://gitlab.com/thorchain/thornode/-/releases/v3.9.0
=> chore: upgrade thorchain v3.9.0

.circleci/config.yml, node/coinstacks/litecoin/api/src/app.ts, node/coinstacks/litecoin/api/src/controller.ts, node/coinstacks/litecoin/sample.env
Contributes to: https://github.com/shapeshift/unchained/issues/1170
=> feat: litecoin on liquify (develop)
