shapeshift/unchained

node/monitoring/loki.ts
node/pulumi/package.json
node/yarn.lock

Configure Loki/Promtail with custom pipelines for Traefik log messages. This will enhance our ability to see what requests are hitting the cluster. 
Update Traefik helm chart to latest version in cluster launcher.
https://github.com/shapeshift/cluster-launcher/pull/13

Traefik observability

---

.circleci/config.yml
node/pulumi/Pulumi.sample.yaml
node/pulumi/package.json

This PR leverages new functionality in [cluster launcher](https://github.com/shapeshift/cluster-launcher/pull/14) that will allow for a horizontal pod autoscaler to be deployed alongside the traefik deployment.
Horizonal pod autoscaling will allow us to ask for less CPU per pod (`500m` --> `300m`) and use less replicas (`7` --> `3`). If the aggregate CPU utilization across all pods exceeds 30%, a new replica will be added to the deployment. With the ability to scale up to 10 replicas.

Traefik Autoscaling

---

.circleci/config.yml

Decrease EBS volume size of RabbitMQ and MongoDB persistent volumes.

Volume Rightsizing

---

node/packages/client/src/bitcoin/websocket.ts
node/packages/client/src/ethereum/websocket.ts

@soptq has [made a PR ](https://github.com/shapeshift/web/pull/1010)to add programmatic login to Cypress.
It now connects to a wallet and starts running tests fast enough that we can end up in a state where we attempt to call `unsubscribeTxs`, and thus, `this.connections.txs?.ws.send(...)`, before we actually have a connected WebSocket.
This causes an exception in Cypress, and stops the tests.
This PR adds a check to ensure we do not attempt to send a payload via a WebSocket connection that is still `CONNECTING`.

fix: check readyState in unsubscribeTxs

---

.circleci/config.yml

We're in the process of configuring CI to deploy to two clusters simultaneously. Because `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are CI environment variables they are placed in the CI environment at the start of every workflow. Due to this the credentials placed in `~/.aws/credentials` aren't read by the AWS CLI in favor of using the default environment variables. 
Refer to the shapeshift specific credentials so that we can remove the defaults.

AWS CI Credentials

---

node/packages/parser/src/types.ts

- `StandardTx` is already a part of `Tx`, so adding it to `SequencedTx` is not necessary
- `parser` can always be defined

chore: parser type improvements

---

.circleci/config.yml

We're currently running 3 bitcoin and ethereum public indexers, scale down to 2.

Scale down indexers

---

node/packages/parser/src/ethereum/index.ts
node/packages/parser/src/ethereum/thor.ts
node/packages/parser/src/ethereum/uniV2.ts
node/packages/parser/src/ethereum/yearn.ts
node/packages/parser/src/ethereum/zrx.ts
node/packages/parser/src/types.ts

- Makes `GenericParser` more generic
- Re-names `ParseTx` to `ParsedTx`
- Uses `BlockbookTx` type alias to be more specific about the Tx type we are using in our parsers
Closes https://github.com/shapeshift/unchained/issues/280

feat: make generic parser more generic

---

.circleci/config.yml

This PR will create smaller EBS volumes in the shapeshift unchained cluster. Once synced we will ensure all environments use the smaller EBS volumes. Cut storage size of RabbitMQ and MongoDB in half.

EBS Rightsize

---

.circleci/config.yml

This PR removes the ethereum-ropsten coinstack. Initially we will destroy pulumi resources, then we will remove ropsten configuration from circleci/config.yaml completely.

Remove Ropsten

---

node/coinstacks/bitcoin/api/src/controller.ts
node/coinstacks/common/api/src/index.ts
node/coinstacks/common/api/src/models.ts
node/coinstacks/ethereum/api/src/controller.ts
node/coinstacks/ethereum/api/src/models.ts

#309
**A few doubts:**
1. Default values for this tx fields: `to`, `gasLimit` and `gasPrice`. (Currently I used "unavailable")
2. Default values for this tokenTransfers fields: `balance` and `contract` . (Currently I used "unavailable")
Let me know if you need anything else.

Transaction history endpoint re-implementation

---

.circleci/config.yml

This PR makes changes to our circleCI config to utilize shapeshift unchained as a development cluster as well as acting as a standby in case the taxistake unchained cluster is unavailable. 
* Remove preview/approve step to deploy dependencies to shapeshift cluster
* Don't deploy dependencies to taxistake cluster during develop workflow
* During main workflow, validate dependencies in shapeshift cluster and preview/approve/deploy dependencies for the first time to taxistake

CI Workflow Improvements

---

.circleci/config.yml

Add cosmos jobs to deploy-main workflow to deploy cosmos API to public unchained clusters.
Remove 2x node group trial, too much churn

Cosmos public

---

node/.lintstagedrc.json

I had expected `.prettierignore` to be honored up front by `lint-staged`, but it turns out that was not the case.
This change explicitly matches file extensions supported by prettier to be linted, in which .prettierignore will then ignore writing files thereafter.

Use explicit glob for prettier formatting

---

go/coinstacks/cosmos/api/handlers.go
go/coinstacks/osmosis/api/handlers.go
go/coinstacks/thorchain/api/handlers.go
go/pkg/cosmos/block.go
go/pkg/cosmos/websocket.go
go/pkg/websocket/registry.go

Only get blocks to put together txs for registered addresses.
Previously we try to get block data for all transactions including ones we dont care about causing it to often print an error message that the block doesnt exist yet because tx is so new.
Now it will only try and get block and print that error message for txs we care about.

Only get blocks to put together txs for registered addresses

---

node/packages/client/package.json
node/packages/client/src/cosmos/parser/index.ts
node/yarn.lock

Replace `{ CAIP10, CAIP19, CAIP2 }` types in `unchained` with `{ AccountId, AssetId, ChainId }`.
There were very few - I'm going to create another issue to remove the caip vernacular on the parsers.
Requires https://github.com/shapeshift/lib/pull/559 to be published.
Closes https://github.com/shapeshift/unchained/issues/395

refactor(caip): rename caip specifiers

---

node/packages/client/src/bitcoin/parser/index.ts
node/packages/client/src/ethereum/parser/index.ts
node/packages/client/src/ethereum/parser/yearn.ts
node/packages/client/src/types.ts

- Removes an unused type, `TxMetadata`
- Use `===` to avoid type coercion bugs
- Remove unnecessary boolean checks

refactor: clean up code

---

node/packages/client/src/bitcoin/parser/__tests__/bitcoin.test.ts
node/packages/client/src/bitcoin/parser/index.ts
node/packages/client/src/cosmos/parser/__tests__/cosmos.test.ts
node/packages/client/src/cosmos/parser/index.ts
node/packages/client/src/cosmos/parser/utils.ts
node/packages/client/src/cosmos/types.ts
node/packages/client/src/ethereum/parser/__tests__/ethereum.test.ts
node/packages/client/src/ethereum/parser/index.ts
node/packages/client/src/ethereum/parser/uniV2.ts
node/packages/client/src/ethereum/parser/weth.ts
node/packages/client/src/types.ts
node/packages/client/src/utils.ts

PR 1/4 to make property names in the parser generic.
Adds new types alongside deprecated ones.
Contributes to https://github.com/shapeshift/unchained/issues/398

chore: replace CAIP property names in the parser with generic names

---

node/coinstacks/common/api/package.json
node/coinstacks/common/api/src/websocket.ts

- Required to be able to pull out unchained-client package into web
- Will be able to remove the dupe type upon removal of the ingester

Remove references to unpublished packages

---

go/pkg/cosmos/api.go

for unknown reasons, websocket connection are not handled correctly for taxistake endpoints via cloudflare dns. this is an attempt to check for websocket upgrades in a better way and hopefully clear up the proxy issue :crossed_fingers:

fix: use upgrade header to check for websocket connection

---

node/coinstacks/avalanche/daemon/init.sh
node/coinstacks/avalanche/pulumi/index.ts
pulumi/src/api.ts
pulumi/src/statefulService.ts

- open host traffic
- use ephemeral certs for unique NodeID on shared volume snapshots
- fix incorrect port mapping
- allow both prod and dev dns to be directed to either cluster

fix: avax config and host match

---

go/coinstacks/osmosis/osmosis.go
go/coinstacks/osmosis/tx.go
go/coinstacks/thorchain/tx.go
go/pkg/cosmos/tx.go

- don't create transfer messages for failed transactions (no value transferred)
- create a message for each side of the swap_exact_amount_in event. (log parsing currently does not support handling of multiple values for same attribute key resulting the `NOTE:` logic)

feat: handle osmosis swap_exact_amount_in

---

node/coinstacks/avalanche/api/src/app.ts
node/coinstacks/bitcoin/api/src/app.ts
node/coinstacks/bitcoin/api/src/controller.ts
node/coinstacks/bitcoincash/api/src/app.ts
node/coinstacks/bitcoincash/api/src/controller.ts
node/coinstacks/common/api/src/utxo/service.ts
node/coinstacks/ethereum/api/src/app.ts
node/coinstacks/litecoin/api/src/app.ts
node/coinstacks/litecoin/api/src/controller.ts

Untested with WS, tested with API endpoints which use the same underlying implementation so we should be 👜.
This PR makes sure we always prefix bitcoincash addresses. Current implementation assumes `bc` or `bitcoincash` prefixes, and simply returns the unparsed address if none of these two prefixes are present, however, blockbook actually requires a prefix.
While at it, also removes the BIP32 / URL Scheme prefix checks for addresses in `formatAddress`. `formatAddress` should take an address as input, if we pass an URL scheme in a method supposed to parse addresses, we have bigger problems. 
- closes https://github.com/shapeshift/unchained/issues/469

feat: prefix q cashaddr with bitcoincash:

---

go/pulumi/src/api.ts

- failed to rebuild api image on changes to `go/{coinstack}/*.go` files

chore: add common golang coinstack files to api hash

---

node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/common/api/src/utils.ts
node/coinstacks/common/api/src/utxo/service.ts

Adds basic validation to page size in UTXO and EVM coinstacks on transaction history endpoints
@kaladinlight - if you prefer to move the MAX_PAGE_SIZE var to somewhere else that could be modified without a code change, let me know.

chore: adds page size validation to all UTXO and EVM coinstacks

---

go/coinstacks/cosmos/api/api.go
go/coinstacks/osmosis/api/api.go
go/pkg/cosmos/api.go

Currently while we do validate the page params, if there is an issue, we continue to process the request. Some examples
https://dev-api.cosmos.shapeshift.com/api/v1/account/cosmos156gqf9837u7d4c4678yt3rl4ls9c5vuuxyhkw6/txs?pageSize=0
https://dev-api.cosmos.shapeshift.com/api/v1/account/cosmos156gqf9837u7d4c4678yt3rl4ls9c5vuuxyhkw6/txs?pageSize=101
https://dev-api.cosmos.shapeshift.com/api/v1/account/cosmos156gqf9837u7d4c4678yt3rl4ls9c5vuuxyhkw6/txs?pageSize=200
In all of these cases, the api does return an error, but still also proceeds to process (or attempt to process) the request with the given page size.
This PR fixes that issue with an early return to avoid attempting to process the request for cosmos and osmosis coin stacks.
It also appears this will fix thorchain as well

fix: early return on bad page params for cosmos / osmosis

---

.circleci/config.yml
pulumi/package.json
pulumi/src/cluster/index.ts
pulumi/yarn.lock

- with multiple blockbook images for different coin support until upstreamed, we are running out of volume size to pull the images causing pods to roll trying to look for available space. increase node worker volume size to give plenty of room and stabilize image pulls

chore: increase eks worker node volume size

---

node/coinstacks/common/api/src/evm/service.ts

Various ERC20 tokens like [Atari](https://etherscan.io/token/0xdacD69347dE42baBfAEcD09dC88958378780FB62) actually have decimals set to 0 which were being filtered out. This change now returns any tokens that have at minimum, a balance and contract address.
Closes https://github.com/shapeshift/web/issues/3167

fix: handle 0 decimal tokens

---

.circleci/config.yml
node/packages/blockbook/Dockerfile

- releases aren't cut often, update branch to master to build from tip
- monkey patch `go-ethereum` module to increase websocket read limit. proposed a less hacky upstream change, but this fixes the issue seen during bsc sync and will wait to hear if martin would like to change or just leave patch.

chore: use master for build and add ws read limit hack

---

go/pkg/websocket/websocket.go

fixes goroutine memory leak for websocket ping ticker. cleanup was being called which stops the ticker, but it does not actually close the channel which results in never terminating the routine. listen to close of `doneChan` to exit goroutine and garbage collect normally

fix: cleanup ticker goroutine on websocket close

---

docs/volumes.md

after moving to ebs-csi, the persistent volume spec changed which wasn't captured by `volumes.md` which is used for manual snapshot/restore. may also be the cause of slower restore speeds as we were still using the legacy ebs controller

chore: update volume doc for ebs csi

---

.circleci/config.yml
node/coinstacks/avalanche/api/package.json
node/coinstacks/avalanche/pulumi/package.json
node/coinstacks/bitcoin/api/package.json
node/coinstacks/bitcoin/pulumi/package.json
node/coinstacks/bitcoincash/api/package.json
node/coinstacks/bitcoincash/pulumi/package.json
node/coinstacks/common/api/package.json
node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/dogecoin/api/package.json
node/coinstacks/dogecoin/pulumi/package.json
node/coinstacks/ethereum/api/package.json
node/coinstacks/ethereum/pulumi/package.json
node/coinstacks/litecoin/api/package.json
node/coinstacks/litecoin/pulumi/package.json
node/coinstacks/optimism/api/package.json
node/coinstacks/optimism/indexer/config.json
node/coinstacks/optimism/pulumi/package.json
node/lerna.json
node/packages/blockbook/package.json
node/packages/blockbook/src/controller.ts
node/packages/blockbook/src/models.ts
node/packages/blockbook/src/swagger.json
node/pulumi/package.json

- blockbook image build from: https://github.com/kaladinlight/blockbook/commit/7d3ea9a97bdb2e946acdc200a6d2911685a5adee
- remove legacy `token` field
- bump package versions

chore: update optimism to blockbook v0.4.0

---

.circleci/config.yml

- there were errors with blockbook tx cache with trying to handle `l1FeeScalar` as hex instead of string

fix(blockbook): handle l1FeeScalar as string versus hex

---

.circleci/config.yml

bsc appears to be really resource hungry at times and was resulting in OOM kills with 12Gi limit. request 12Gi for cost/provisioning purposes, but allow burst up to 24Gi.

chore: tweak bsc resources to avoid OOM kill

---

.circleci/config.yml

https://github.com/prysmaticlabs/prysm/releases/tag/v4.0.0
**This release is mandatory for all mainnet Prsym beacon nodes and validators. The release enables Capella upgrade, scheduled on April 12, 2023, 10:27:35pm UTC and epoch 194048. Failure to upgrade will result in your node forking off the chain and the validator losing rewards and getting penalized for being offline.**

chore: upgrade prysm v3.2.2 -> v4.0.0

---

.circleci/config.yml

https://github.com/bnb-chain/bsc/releases/tag/v1.1.21
**The mainnet is expected to have a scheduled hardfork upgrade named Planck at block height 27,281,024. The current block generation speed forecasts this to occur around 12th April 2023 at 05:30 AM (UTC).**

chore: upgrade bsc v1.1.20 -> v1.1.21

---

.circleci/config.yml
go/coinstacks/cosmos/pulumi/index.ts
go/coinstacks/osmosis/pulumi/index.ts
go/coinstacks/thorchain/pulumi/index.ts
node/coinstacks/avalanche/pulumi/index.ts
node/coinstacks/bitcoin/pulumi/index.ts
node/coinstacks/bitcoincash/pulumi/index.ts
node/coinstacks/bnbsmartchain/pulumi/index.ts
node/coinstacks/dogecoin/pulumi/index.ts
node/coinstacks/ethereum/pulumi/index.ts
node/coinstacks/litecoin/pulumi/index.ts
node/coinstacks/optimism/pulumi/index.ts
pulumi/src/api.ts
pulumi/src/config.ts
pulumi/src/index.ts
pulumi/src/statefulService.ts
pulumi/volumeReaper/src/volumeReaper.ts

The problem:
It is currently impossible to reliably test non-default coinstack configuration, as the some names are propagated downstream in multiple ways and require certain values to be set to defaults in order to work. 
Examples include:
`const [coinstack] = asset.split('-')`
`const { hash: apiHash } = await hashElement(`../../${coinstack}/api`, `
`const name = `${args.asset}-${args.config.name}`
The combination of these makes it impossible to change the name of deployed resources. Also the terms `name`, `asset`, `service` are used inconsitently, i.e. a parameter passed down as `name` is received as `app` downstream, further complicating debugging of naming issues.
I'd like to introduce a shared top-down naming scheme that will make it obvious which resources will be referenced, where, …

feat: naming unification

---

k6/Makefile
node/coinstacks/avalanche/indexer/Makefile
node/coinstacks/bitcoin/indexer/Makefile
node/coinstacks/bitcoincash/indexer/Makefile
node/coinstacks/bnbsmartchain/indexer/Makefile
node/coinstacks/dogecoin/indexer/Makefile
node/coinstacks/ethereum/indexer/Makefile
node/coinstacks/litecoin/indexer/Makefile
node/coinstacks/optimism/indexer/Makefile
node/packages/blockbook/Makefile
pulumi/src/docker.ts

When images are built locally on M1 macs, they're built and pushed with aarch64 architecture, which is incompatible with our nodes. This additional argument has no effect on x64 systems, but builds correct images when on a different architecture

fix: Always build x64 docker images

---

node/coinstacks/bnbsmartchain/daemon/init.sh

https://github.com/bnb-chain/bsc/issues/1437
nodes have been getting stuck and the current suggested fix is to manual reset all static peers for the node. add `hard_reset_peers` startup func so we get a fresh peer state on boot to help combat the buggy peering logic on bsc...

feat: add hard reset of static peers on node start

---

.circleci/config.yml

Because both polygon and bnb are more likely to fail than other chains, it would be wise to snapshot them more often and keep 2 backups instead of one. Sat and wed seem like good dates, as we're unlikely to not notice broken chains over a week's period

feat: biweekly backups for the bad kids

---

monitoring/src/grafana.ts

The `ingressroute` currently points at `unchained-grafana`, whereas the `svc` name is `grafana`

fix: grafana svc route

---

.circleci/config.yml

if prysm falls behind, it pulls in copious amounts of data into memory to spin back up. increase mem to buffer and avoid OOM kill

chore: increase prysm memory

---

node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/common/api/src/evm/types.ts
node/coinstacks/gnosis/api/src/app.ts

Introduces an additional RPC method for fetching internal tx's. By default all existing transactions use the `debug` mode, while for `gnosis` we use the new `trace` mode to address current performance problems.
The trace module has been confirm to be much less resource heavy. The memory usage never spiked over 1 MB after the change. 
Local test result with Gnosis:

chore: trace method for internal tx

---

.circleci/config.yml
node/coinstacks/dogecoin/daemon/Dockerfile

https://github.com/dogecoin/dogecoin/releases/tag/v1.14.6
- also increases blockbook memory more (still seeing OOM kills)

chore: upgrade dogecoin v1.14.5 -> v1.14.6

---

.circleci/config.yml
monitoring/my-kube-prometheus/unchained-kube-promstack.jsonnet
pulumi/src/ipfs/ipfs.ts

- traefik looks to be a bit overloaded, increase memory and allow further scaling if needed
- increase ipfs node resources
- increase kube state metrics proxy resources (configured via promstack.jsonnet)

chore: update configs to resolve unchained alerts

---

docker-compose.yml
go/coinstacks/cosmos/docker-compose.yml
go/coinstacks/osmosis/docker-compose.yml
go/coinstacks/thorchain/docker-compose.yml
node/coinstacks/avalanche/docker-compose.yml
node/coinstacks/bitcoin/docker-compose.yml
node/coinstacks/bitcoincash/docker-compose.yml
node/coinstacks/bnbsmartchain/docker-compose.yml
node/coinstacks/common/api/src/evm/gasOracle.ts
node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/dogecoin/docker-compose.yml
node/coinstacks/ethereum/docker-compose.yml
node/coinstacks/gnosis/docker-compose.yml
node/coinstacks/litecoin/docker-compose.yml
node/coinstacks/optimism/docker-compose.yml
node/coinstacks/polygon/docker-compose.yml
package.json
yarn.lock

- recent docker update broke the existing networking. add `external` networks to each coinstack service
- lots of log spew from gas oracle on missing block due to querying load balanced nodes for new block faster than it propagates to all nodes. retry with back off added
- errors when fetching tx history for contracts due to 0 value `create` calls being returned from etherscan. filter out any 0 value internal transactions.
- upgrade some common dependency packages that have gotten pretty out of date

chore: house keeping items

---

.circleci/config.yml

https://github.com/cosmos/gaia/releases/tag/v11.0.0
https://github.com/ethereum/go-ethereum/releases/tag/v1.12.2
https://github.com/ava-labs/avalanchego/releases/tag/v1.10.8
https://gitlab.com/thorchain/midgard/-/releases/2.16.2
https://github.com/ethereum-optimism/optimism/releases/tag/v1.1.2

chore: upgrade nodes to latest

---

node/coinstacks/bnbsmartchain/api/src/controller.ts
node/coinstacks/bnbsmartchain/api/src/swagger.json
node/coinstacks/bnbsmartchain/daemon/init.sh
node/coinstacks/common/api/src/evm/gasOracle.ts

- validator txs don't cost any gas and throw off the gas oracle pricing
- new `config.toml` provided by bnb set min gas limit to 3 gwei, support 1 gwei min limit

fix: omit 0 gas price and allow 1 gwei broadcast

---

.circleci/config.yml
docs/restore-pvc.yaml
go/coinstacks/thorchain/daemon/readiness.sh
go/scripts/tendermint.sh
monitoring/src/index.ts
node/scripts/evm.sh
pulumi/package.json
pulumi/src/index.ts
pulumi/src/ipfs/ipfs.ts
pulumi/src/statefulService.ts

In an effort to reduce the cost of the unchained infra, update all volumes from `gp2` to `gp3` which should result in a ~10% cost reduction across the board. This will also provide optional configuration for tuning iops and throughput parameters for nodes that struggle to stay in sync.
- update cluster launcher to support `gp3` volume types with newest version of `ebs-csi-driver`
- update all coinstacks to use `gp3` volumes with baseline defaults (coinstacks that struggle to stay in sync are using comparable iops/throughput as the `gp2` counterpart and will allow for further fine tuning)
- update any out of date nodes
- update volume restore yaml with `gp3` volume type

feat: ebs gp3 upgrade

---

node/coinstacks/avalanche/api/src/controller.ts
node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/common/api/src/evm/types.ts

api.snowtrace.io is being sunset on November 30th, use the routescan replacement for avalanche.
- internal tx types were updated to distinguish internal txs by address or tx hash
- additional filtering was added to remove non internal txs that were being returned from routescan...
- we will not need to update block explorer urls client side as https://snowtrace.io will be redirected to the new backend being hosted by Avascan on November 30th (https://twitter.com/avax/status/1719005686196322525)

chore: update avalanche explorer api

---

.circleci/config.yml
node/coinstacks/bitcoin/pulumi/index.ts
node/coinstacks/bitcoincash/pulumi/index.ts
node/coinstacks/bnbsmartchain/daemon/init.sh
node/coinstacks/dogecoin/pulumi/index.ts
node/coinstacks/ethereum/pulumi/index.ts
node/coinstacks/litecoin/pulumi/index.ts
node/coinstacks/polygon/daemon/init.sh
node/coinstacks/polygon/pulumi/index.ts
node/packages/blockbook/src/constants.ts

Updates:
- https://github.com/bnb-chain/bsc/releases/tag/v1.3.4
- supports hardfork
- replace `-txlookuplimit` with `-history.transactions`
- https://github.com/maticnetwork/bor/releases/tag/v1.2.0
- https://github.com/ava-labs/avalanchego/releases/tag/v1.10.17
- https://github.com/NethermindEth/nethermind/releases/tag/1.23.0
Polygon:
- increase memory (bor is just turning into a bloated pig that makes bsc look stable and lean :sob:)
- always pull in genesis file so we don't halt for the next hard fork
Blockbook:
- remove `-workers` flag because it turns out it has no effect on stay sync mode
- add `-dbcache` in an attempt to reduce memory footprint (seeing more and more OOM kills on blockbook instances)
Misc:
- right size resources and volumes

chore: infra updates

---

.circleci/config.yml
go/coinstacks/cosmos/daemon/init.sh

- bsc was OOM killing. increase memory to prevent this
- cosmos has been having issues staying synced. do not use persistent peers and just use a single stable polkachu peer

chore: increase bsc memory and update cosmos peering

---

docker-compose.yml

Attempting to run lerna watch locally in docker would fail due to how we copied over node_modules into the linux container if using a mac.  Adding yarn install to the compose enforces that the platform specific version of @nx/nx-linux-arm64-musl is installed and seems to fix the issues.

fix: resolves issues when running in docker on mac

---

node/coinstacks/common/api/src/evm/service.ts

routescan fixed their api response for internal transactions and filtering out `traceId` 0 was actually invalid as there are transactions with a single callstack that are valid internal transactions that we should be detecting (thorchain outbound).

fix: do not filter traceId 0

---

go/coinstacks/thorchain/api/handler.go
go/coinstacks/thorchain/api/types.go
go/coinstacks/thorchain/thorchain.go
go/coinstacks/thorchain/tx.go

- cleanup synthetic `ResultTx` fields for clarity
- use correct `to` address for deposit messages that result in a `withraw` or `refund` event
- add synthetic outbound messages for multi action transactions (ex. lp withdrawal contains the withdrawal request and the withdrawal outbound transfer)

feat: improve thorchain deposit transaction parsing

---

.circleci/config.yml
node/coinstacks/gnosis/pulumi/index.ts

Blockbook is struggling to stay in sync for gnosis. This temp fix disables the readiness probe and uses the patched blockbook image that will serve data even if not in sync (balances will still be accurate as they are fetched on chain, but tx history can be off/behind).

fix: gnosis indexer patch

---

.circleci/config.yml
node/coinstacks/optimism/op-node/init.sh
node/coinstacks/optimism/pulumi/index.ts

- https://github.com/ethereum/go-ethereum/releases/tag/v1.13.12
- https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.1
- https://github.com/ava-labs/avalanchego/releases/tag/v1.10.19
- https://gitlab.com/thorchain/thornode/-/releases/v1.127.2
- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101308.0
- https://github.com/ethereum-optimism/optimism/releases/tag/v1.5.1
- https://github.com/NethermindEth/nethermind/releases/tag/1.25.4
- https://github.com/OffchainLabs/nitro/releases/tag/v2.2.4

chore: update nodes and scale down dev sts replaced by nownodes

---

.circleci/config.yml

Cut over remaining prod coinstacks to nownodes for currently supported chains

chore: prod cutover to nownodes

---

.circleci/config.yml
node/coinstacks/arbitrum-nova/pulumi/index.ts
node/coinstacks/arbitrum/pulumi/index.ts
node/coinstacks/optimism/pulumi/index.ts
node/coinstacks/polygon/pulumi/index.ts

- scale for nownodes usage
- use prod l1 endpoints to allow us to scale down dev eth coinstack

chore: coinstack modifications

---

node/coinstacks/arbitrum/api/src/app.ts
node/coinstacks/bnbsmartchain/api/src/app.ts
node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/common/api/src/registry.ts
node/coinstacks/common/api/src/websocket.ts
node/coinstacks/ethereum/api/src/app.ts
node/coinstacks/polygon/api/src/app.ts

Our current trace transaction setup requires way too many requests for use against nownodes endpoints. Add trace block functionality and use for currently supported nownodes coinstacks.

feat: evm block trace

---

.circleci/config.yml

Cosmos is now managed from `cosmos` branch for the time being

chore: remove cosmos deployment from develop and main

---

.circleci/config.yml

- Right size instances post nownodes infra downgrade
- Update CI dependencies
- Remove arbitrum nova
- Upgrade nodes:
- https://github.com/ava-labs/avalanchego/releases/tag/v1.11.3
- https://gitlab.com/thorchain/thornode/-/releases/v1.130.1
- https://github.com/ethereum-optimism/optimism/releases/tag/v1.7.2
- https://github.com/sigp/lighthouse/releases/tag/v5.1.2

chore: upgrades and right sizing

---

node/coinstacks/arbitrum-nova/api/src/app.ts
node/coinstacks/arbitrum/api/src/app.ts
node/coinstacks/avalanche/api/src/app.ts
node/coinstacks/bitcoin/api/src/app.ts
node/coinstacks/bitcoincash/api/src/app.ts
node/coinstacks/bnbsmartchain/api/src/app.ts
node/coinstacks/common/api/src/registry.ts
node/coinstacks/common/api/src/websocket.ts
node/coinstacks/dogecoin/api/src/app.ts
node/coinstacks/ethereum/api/src/app.ts
node/coinstacks/gnosis/api/src/app.ts
node/coinstacks/litecoin/api/src/app.ts
node/coinstacks/optimism/api/src/app.ts
node/coinstacks/polygon/api/src/app.ts
node/packages/blockbook/src/index.ts
node/packages/blockbook/src/websocket.ts

- leverage blockbook `subscribeAddresses` to filter mempool transactions to only those we care about. this will reduce both nownodes req usage and also lower aws data transfer which will save us $$$
- update all evm `blockHandler` functions to leverage trace by block to unify approach and also reduce request made to nownodes for avalanche which will save us more $$$

feat: blockbook subscribe addresses

---

node/coinstacks/arbitrum-nova/api/src/controller.ts
node/coinstacks/arbitrum-nova/api/src/swagger.json
node/coinstacks/arbitrum/api/src/controller.ts
node/coinstacks/arbitrum/api/src/swagger.json
node/coinstacks/avalanche/api/src/controller.ts
node/coinstacks/avalanche/api/src/swagger.json
node/coinstacks/bnbsmartchain/api/src/controller.ts
node/coinstacks/bnbsmartchain/api/src/swagger.json
node/coinstacks/common/api/src/evm/controller.ts
node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/common/api/src/models.ts
node/coinstacks/common/api/src/types.ts
node/coinstacks/ethereum/api/src/controller.ts
node/coinstacks/ethereum/api/src/swagger.json
node/coinstacks/gnosis/api/src/controller.ts
node/coinstacks/gnosis/api/src/swagger.json
node/coinstacks/optimism/api/src/controller.ts
node/coinstacks/optimism/api/src/swagger.json
node/coinstacks/polygon/api/src/controller.ts
node/coinstacks/polygon/api/src/swagger.json

- add `/jsonrpc` endpoint to unchained api to proxy raw node requests
- this will allow us to remove api gateway proxy doing the same thing and lower overhead and hopefully spend $
- dry up evm api with a common controller for shared/identical endpoints

feat: add jsonrpc endpoint to unchained api

---

.circleci/config.yml
node/packages/blockbook/Dockerfile

- upgrade blockbook to latest master
- rebase optimism, arbitrum and gnosis forks with latest master
- fix gnosis block sync (post dencun upgrade) and add additional patch to process mempool before initial sync is finished

chore: upgrade blockbook

---

node/packages/blockbook/Dockerfile

Update the sed command for patching the websocket read limit for go-ethereum. The default is 32 and this was blown out by bsc recently prompting the fix/update.

fix: patch ws read limit

---

.circleci/config.yml

Fully scale down tier two coinstacks for 100% reliance on nownodes.

chore: scale down tier two coinstacks

---

.circleci/config.yml

Add a separate fallback deployment pipeline to allow us to easily cut back and forth from nownodes -> self hosted if needed for tier one coinstacks.

feat: add self hosted fallback deployment pipeline

---

.circleci/config.yml
go/coinstacks/thorchain/daemon/init.sh

https://gitlab.com/thorchain/thornode/-/tree/v1.131.0?ref_type=tags
This release introduced the experimental buffer configs which have been set and updated to 5k to ensure websockets will stay open and healthy even through periods of high tx congestion (successfully process <5k txs in a block). During the last period I was seeing spikes upwards of 3k, so this adds a pretty healthy buffer that obviously can be tweaked in the future if needed.

chore: upgrade thorchain v1.130.1 -> v1.131.1

---

node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/common/api/src/index.ts
node/coinstacks/common/api/src/middleware.ts

- use common `handleError` func for all evm service functions
- extend api error class slightly
- narrow on constructor name and response with api error message

chore: respond with api error message

---

.circleci/config.yml

bye bye. full reliance on nownodes for litecoin and bnbsmartchain

chore: scale down litecoin and bnbsmartchain

---

node/coinstacks/common/api/src/utxo/service.ts
node/packages/blockbook/src/controller.ts
node/packages/blockbook/src/models.ts
node/packages/blockbook/src/swagger.json

Due to websocket connection issues against nownodes blockbook instances (presumably connection limits or rate limits), we are unable to reliably use blockbook websockets to estimate fees for utxo chains. This update leverages the blockbook rest endpoint for estimating fees instead.
Note: this increases our request count consumption from 1 request to 3 requests for every estimate call, so if/when nownodes fixes their websocket connections, we may want to switch back, but considering the `/fees` endpoint isn't heavily used, there probably won't be too drastic of a difference.

fix: switch utxo fee estimation from websocket to http

---

.circleci/config.yml
go/cmd/thorchain/main.go
go/coinstacks/thorchain/api/affiliateFees.go
go/coinstacks/thorchain/api/api.go
go/coinstacks/thorchain/api/handler.go
go/coinstacks/thorchain/api/swagger.json
go/coinstacks/thorchain/api/types.go
go/pkg/cosmos/block.go

- Added in memory affiliate fee indexer for shapeshift affiliate address
- Added websocket to listen for new affiliate fees
- Added endpoint to allow querying affiliate fees by unix timestamp range
- Increased thornode memory limit to handle indexing burden

feat: affiliate fees indexer and endpoint

---

.circleci/config.yml
node/coinstacks/bitcoin/api/src/controller.ts
node/coinstacks/bitcoin/sample.env
node/coinstacks/bitcoincash/api/src/controller.ts
node/coinstacks/bitcoincash/sample.env
node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/common/api/src/utils.ts
node/coinstacks/common/api/src/utxo/service.ts
node/coinstacks/dogecoin/api/src/controller.ts
node/coinstacks/dogecoin/sample.env
node/coinstacks/litecoin/api/src/controller.ts
node/coinstacks/litecoin/sample.env

Sends were being sent through blockbook which also had a retry which resulted in 520 responses on failed sends due to timeouts and thereby not returning any useful error response message as to why the send failed. Update `/send` to use raw jsonrpc calls with no retry to ensure the send fails within expected timeout and return useful error message for debugging purposes.

feat: update send endpoints to use raw jsonrpc

---

go/cmd/cosmos/main.go
go/pkg/cosmos/cosmos.go
go/pkg/cosmos/fees.go

Latest fork of cosmos removed the `globalfee` module and replaced it with `feemarket` module. Update the Unchained API to fetch minimum gas prices from the new `feemarket` module
https://github.com/cosmos/gaia/pull/3028

fix: upgrade globalfee module -> feemarket module

---

.circleci/config.yml
node/coinstacks/optimism/api/src/controller.ts

- scale down optimism in dev env 1 -> 0
- scale down optimism in prod env 2 -> 1
- update fees rpc requests to be concurrent to improve response times

chore: scale down optimism

---

go/coinstacks/thorchain-v1/daemon/init.sh
go/coinstacks/thorchain/daemon/readiness.sh

- start thornode directly for legacy (render-config is broken post fork)
- disable p2p for legacy
- update readiness endpoint

chore: follow up updates for thorchain hard fork

---

.circleci/config.yml
node/coinstacks/base/daemon/init.sh

- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101408.0
- https://github.com/ethereum-optimism/optimism/releases/tag/v1.9.1

chore: upgrade base node stack

---

monitoring/src/alertmanager/config.yaml

No need to alert on volume size for `thorchain-v1` as it is a static archive volume now.

chore: disable volume alert for thorchain-v1

---

go/cmd/thorchain-v1/main.go
go/cmd/thorchain-v1/sample.env
go/coinstacks/thorchain-v1/api/api.go
go/coinstacks/thorchain-v1/api/handler.go
go/coinstacks/thorchain-v1/api/websocket.go
go/pkg/cosmos/handler.go

Leverage `thorchain-1` websockets to update `BlockService.Latest.Height` on `newBlockHeader`. This ensures we can accurately calculate the number of confirmations on `thorchain-v1` transactions.

fix: thorchain-v1 confirmations

---

node/coinstacks/common/api/src/utxo/service.ts

With the upcoming addition of phantom wallet which only supports a single address for bitcoin (no account xpub exposed), it was noticed that the responses were not conforming to the queries by xpub. Update to conform as closely as possible (note we cannot determine the derivation path for `/utxo` endpoint)

feat: update response of utxo chain queries by address

---

node/coinstacks/solana/api/package.json
node/coinstacks/solana/api/src/controller.ts
node/coinstacks/solana/api/src/models.ts
node/coinstacks/solana/api/src/swagger.json
yarn.lock

- `getToken` endpoint to allow us to get token information like 'decimals', 'name', 'symbol' which are not present on the transaction history responses
- cache tokens to improve performance

feat: add solana get token endpoint

---

node/coinstacks/common/api/src/evm/service.ts
node/coinstacks/common/api/src/utils.ts
node/coinstacks/solana/api/src/utils.ts
node/coinstacks/solana/api/src/websocket.ts

Use of `finalized` commit level on `logsSubscribe` subscription resulted in frequent missed transactions logs. Update to use `confirmed` commit level to ensure stable transaction log subscriptions and increase the retry for `getTransaction` to allot up to 1 minutes of retries to ensure there is time for the transaction to be finalized on chain and subsequently returned from the helius `/transactions` endpoint.

fix: use confirmed commit level for logsSubscribe

---

node/coinstacks/common/api/src/websocket.ts

Properly handle empty subscription id as a means of unsubscribing from all subscriptions for a client.

fix: handle unsubscribe all correctly

---

.circleci/config.yml
node/packages/blockbook/Dockerfile

- Upgrade blockbook to latest main commit (supports bitcoin upgrade)
- https://github.com/bitcoin/bitcoin/releases/tag/v28.0
- https://github.com/ethereum/go-ethereum/releases/tag/v1.14.12
- https://gitlab.com/thorchain/thornode/-/releases/v2.137.3
- https://gitlab.com/thorchain/midgard/-/releases/2.26.0
- https://github.com/sigp/lighthouse/releases/tag/v6.0.0
- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101411.2
- https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.10.0

chore: upgrade backend to latest versions

---

pulumi/src/ipfs/configure-ipfs.sh

Previously we were exiting if an ipfs config already existed resulting in the inability to reconfigure ipfs. Update logic to init config if it doesn't exist and still allow for updating/changing config thereafter.

fix: configure ipfs from init container

---

node/coinstacks/bitcoin/daemon/init.sh

Blockbook is not handling the new rpc updates as of v28.0. Make sure deprecated rpc endpoint only return warnings so blockbook can still sync.

fix: bitcoin deprecatedrpc warnings

---

pulumi/src/ipfs/configure-ipfs.sh

https://github.com/shapeshift/unchained/pull/1075 supported updating the configuration of ipfs, but failed to set the correct ownership of the config after update. This change sort all init/update/ownership issues with ipfs.

fix: set ipfs ownership to correct user

---

.circleci/config.yml
node/coinstacks/base/indexer/config.json
node/coinstacks/base/pulumi/index.ts
node/packages/blockbook/src/websocket.ts

- no erc1155 indexing
- increase db max open files
- increase block addresses cache
- https://github.com/ethereum-optimism/op-geth/releases/tag/v1.101411.7
- https://github.com/ethereum/go-ethereum/releases/tag/v1.15.0

chore: base performance updates

---

.circleci/config.yml

- right size based on last 7 day usage patterns
- use limit only to try and improve pod scheduling and reduce overall eviction rate
- tune dev vs prod to reduce overall resource usage more accurately

chore: right size infra

---

pulumi/src/ipfs/entrypoint.sh
pulumi/src/ipfs/ipfs.ts

ipfs cluster peering has recently died resulting in the inability to fetch new ipfs content. first attempt fix at dns bootstrapping.

chore: update ipfs config

---

.circleci/config.yml
pulumi/src/ipfs/entrypoint.sh
pulumi/src/ipfs/ipfs.ts
pulumi/src/statefulService.ts

- Our ipfs cluster was broken after recent updates to `go-ipfs` and `ipfs-cluster`. These updates configure the cluster correctly to ensure bootstrapping works as intended and fetching ipfs content is happy again.
- Add `patchForce` pulumi annotation to our stateful sets, to allow updates against state that has been changed by another controller (CI fix)

fix: ipfs cluster config

---

.circleci/config.yml
node/coinstacks/base/daemon/init.sh
node/coinstacks/base/op-node/init.sh
node/coinstacks/base/pulumi/index.ts

- https://gitlab.com/thorchain/thornode/-/releases/v3.7.0
- https://gitlab.com/thorchain/midgard/-/releases/2.32.6
- https://github.com/ethereum/go-ethereum/releases/tag/v1.16.1
- https://github.com/OffchainLabs/prysm/releases/tag/v6.0.4
- https://github.com/NethermindEth/nethermind/releases/tag/1.32.2
- https://github.com/paradigmxyz/reth/releases/tag/v1.5.0
- https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.13.4

chore: node version updates and switch base from op-geth to reth
